### PR TITLE
27 daps references

### PR DESCRIPTION
**Pull request by bellebaum**
This PR adresses Issue #27 by rewriting and restructuring the DAPS Specification.
It also separates the Connector IDs into their own file for later reference from other files.

### CODE REVIEW

**Comment by sebplorenz** [comment]
Hi,
it is written that Connector IDs should be in the form SKI:AKI. What is the scope of this statement? Is the scope limited to the internals of the identity provider? Or is the intention to use SKI:AKI as the IDS wide connector identifier (meaning that the business identifier for a connector becomes the SKI:AKI key)?
What is then the meaning of  ids:connectorDescription - @Id? Should it be replaced with the SKI:AKI, or how do they relate?

**Comment by bellebaum** [comment]
Hi @sebplorenz ,
That is something I copied from the current version. This PR is only supposed to be more precise in terms of references to existing specifications, to avoid confusion and inconsistencies. Generally, it should not include normative changes.

I remember there being some discussion about different identifiers in the IDS ecosystem [here](https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/885#issuecomment-1030801528).

I would assume that it needs to be known to the certification body and the DAPS at a minimum, depending on where the DAPS gets its data from.

**Comment by bellebaum** [comment]
Changes have already been addressed

**Comment by sebplorenz** [comment]
@bellebaum Can you please link here where/how this has been addressed.

**Comment by bellebaum** [comment]
@sebplorenz https://github.com/International-Data-Spaces-Association/IDS-G/commit/6c3b57916ea1d2792b6a0447fafab7d23b65110a

This commit addressed the missing references to underlying specifications.

**Pull request closed without merging**
