### PR TITLE
Feature/broker links

### PR DESCRIPTION
**Pull request by sebbader**
Adding:
* Link to the Broker Specification Document (no Jive-internal anymore)
* adding more info to the IM descriptions
* adding contact information for the IAIS Maven repo

### CODE REVIEW

**Comment by ssteinbuss** [comment]
Please comment on this Pull request to get this done.

**Comment by ssteinbuss** [comment]
Please check the link to the Fraunhofer repo @sebbader

**Comment by sebbader** [comment]
@ssteinbuss Done with the updates, this PR is ready to be merged.

**Review by ssteinbuss — APPROVED** [review]
Fine for me.

**Pull request merged**
